---
aws-region : 'eu-west-1'
cs-bootstrap-name : 'cs-bootstrap'
cs-agent-name : 'consul-agent'
cs-server-name : 'cs-server'

mongodb-create-db : true
mongodb-name : 'tradefinance'
mongodb-user : 'tradefinance'
mongodb-hash-passwd : 'a15fbfca5e3a758be80ceaf42458bcd8'

cszk-hosts  :
  - '192.168.10.21'
  - '192.168.10.22'

cszk-hosts-with-bootstrap  :
  - '192.168.10.20'
  - '192.168.10.21'
  - '192.168.10.22'

zk-election-port :  2889
zk-leader-port :  3889
zk1-ip-address :  '192.168.10.20'
zk2-ip-address :  '192.168.10.21'
zk3-ip-address :  '192.168.10.22'

nodejs-version : '5.x'

# content tools 
ct-repo-user : 'dieple'
ct-repo-user-rsa-id : '/home/vagrant/.ssh/id_rsa'
ct-repo-url :
  - git@github.com:dieple/jhipster-2.23.0.git

ct-checkout-path :
  - /opt/app/content-tools


